/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog2.vista;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import prog2.model.EstacioTren;

/**
 *
 * @author Hatuey
 */
public class AppEstacio extends javax.swing.JFrame {
    
    EstacioTren estacio;

    /**
     * Creates new form AppEstacio
     */
    public AppEstacio(EstacioTren estacio){
        initComponents();
        this.estacio = estacio;
        try{
            estacio.inicialitzaDadesEstacioTren();
        }
        catch(ExcepcioEstacio e){
            JOptionPane.showMessageDialog(this,"Estació guardada correctament", "Guardat correcte", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        btnIncidencies = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFitxer = new javax.swing.JMenu();
        opcioGuardar = new javax.swing.JMenuItem();
        OpcioCarregar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("ESTACIO UB");

        btnConsulta.setText("Consultar Dades Estació");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnIncidencies.setText("Agregar/Eliminar incidències");
        btnIncidencies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncidenciesActionPerformed(evt);
            }
        });

        mnFitxer.setText("Fitxer");
        mnFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFitxerActionPerformed(evt);
            }
        });

        opcioGuardar.setText("Guardar");
        opcioGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioGuardarActionPerformed(evt);
            }
        });
        mnFitxer.add(opcioGuardar);

        OpcioCarregar.setText("Carregar");
        OpcioCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcioCarregarActionPerformed(evt);
            }
        });
        mnFitxer.add(OpcioCarregar);

        jMenuBar1.add(mnFitxer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsulta)
                    .addComponent(btnIncidencies))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsulta)
                .addGap(18, 18, 18)
                .addComponent(btnIncidencies)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        new ConsultaEstacio(this, true,estacio).setVisible(true);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnIncidenciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncidenciesActionPerformed
        // TODO add your handling code here:
        new CreaIncidencia(this,true,estacio).setVisible(true);
    }//GEN-LAST:event_btnIncidenciesActionPerformed

    private void mnFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFitxerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnFitxerActionPerformed

    private void opcioGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioGuardarActionPerformed
        // TODO add your handling code here:
                JFileChooser filechooser = new JFileChooser();
        int option = filechooser.showSaveDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = filechooser.getSelectedFile();
            try{
             estacio.guardar(file.getAbsolutePath()); 
             JOptionPane.showMessageDialog(this,"Estació guardada correctament", "Guardat correcte", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(ExcepcioEstacio e){
                JOptionPane.showMessageDialog(this,"Error al guarda estació: " + e.getMessage(), "Error guardat", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_opcioGuardarActionPerformed

    private void OpcioCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcioCarregarActionPerformed
        // TODO add your handling code here:
        
                JFileChooser filechooser = new JFileChooser();
        int option = filechooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = filechooser.getSelectedFile();
            try{
             EstacioTren estacioCarregada = estacio.carregar(file.getAbsolutePath()); 
             estacio = estacioCarregada;
             JOptionPane.showMessageDialog(this,"Estació carregada correctament", "Carregat correcte", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(ExcepcioEstacio e){
                JOptionPane.showMessageDialog(this,"Error al carregar estació: " + e.getMessage(), "Error carregat", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_OpcioCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEstacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEstacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEstacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEstacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstacioTren estacio = new EstacioTren("Green");
                new AppEstacio(estacio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OpcioCarregar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnIncidencies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnFitxer;
    private javax.swing.JMenuItem opcioGuardar;
    // End of variables declaration//GEN-END:variables
}
